### PR TITLE
update v5.4

### PR DESCRIPTION
**Pull request by tabuna**

### CODE REVIEW

**Comment by RachidLaasri** [comment]
Thanks!

**Comment by alexcroox** [comment]
@RachidLaasri should the repo description be updated?

"A web installer for Laravel 5.1"

**Comment by RachidLaasri** [comment]
I'll tag a new version and update the description! Thanks for the reminder.

**Comment by vitor-adonai** [comment]
Nice package.Work in Laravel 5.4 = :-D

**Pull request merged**
