### PR TITLE
Dev update

### PR DESCRIPTION
**Pull request by alanpilloud**
Add an /update route.

If the install has not been ran, the script redirects to /install.
If there are no migrations to run, the script aborts with 404.

En and Fr translations have been done.

### CODE REVIEW

**Comment by renztoygwapo** [comment]
amazing :)

**Comment by RachidLaasri** [comment]
This is really cool, I'll review the changes you made recently and merge them ASAP. Thank you

**Comment by alanpilloud** [comment]
My pleasure. Let me know if anything doesn't meet your standards.

**Comment by RachidLaasri** [comment]
Thanks a lot.

**Pull request merged**
