### PR TITLE
Proper PSR-4

### PR DESCRIPTION
**Pull request by jmverges**
Hi!

I just did a bit of refactor to have proper PSR-4 and fixed some code warning the IDE was telling me ;)

Hope you feel it well.

Cheers,
Juan Manuel.

### CODE REVIEW

**Comment by jeremykenedy** [comment]
It was PSR-4 compliant before, having the resources outside of the src directory is more of an opinion.

**Comment by jmverges** [comment]
Of course it is PSR-4 but there is inconsistency in the src folder, as it is not used for only PSR-4 purpose.

 A few examples:
https://github.com/laravel/horizon
https://github.com/laravel/cashier
https://github.com/laravel/scout

As you can see in all of them, under src folder there are only files with namespaces which provides a more clearer vision of what is going on. In general, you can see how Laravel 5.4 has been going to that direction. In general, a package based on laravel, should have the same structure as https://github.com/laravel/laravel but change folder app for src 

I also need to add, that I solved a some issues around:
- Having canUpdate and canInstall with lowerCamelCase is not correct.
- Deleted some dependencies with namespaces outside the package (all the files having a `extend` or `use` with `App\`) is not correct as  you may not use such namespace in you real application if you don't use the boilerplate laravel/laravel for example: https://github.com/hourglass/hourglass

I also fixed the dependency with default `App` based `DataSeeder` as this is also can vary from one project to other one.

Of course guys, this is your package and I will understand if you don't want to include code from a stranger like me :D but I didn't do anything based on a whim, just found this package interesting when a workmate show us and I though to give it a try and spend some hours to improve it back to the community as we maybe will use it at work.


Cheers 👍

**Comment by jeremykenedy** [comment]
I am not the package author, @RachidLaasri is. I am just a fan that liked the package a lot and contributed like you 😄

**Comment by RachidLaasri** [comment]
Thank you @jmverges for the amazing work you have done, I haven't merged it not because "you are a stranger" as you said, that definitely has nothing to do with the reason I haven't merged it.

It's just because I like the current structure and I tried to keep it similar to what Laravel has. That's all.

Once again thank you a lot for your contribution and the time you spent working on this.

**Comment by jmverges** [comment]
@RachidLaasri as you can see in official packages from Laravel, like spark, scout etc, they are following the structure I proposed, so "keep it similar to what Laravel has" doesn't match with the current structure, maybe for old version of Laravel, but not for current ones.

Anyway, your code, your decision ;) cheers.

**Pull request closed without merging**
