### PR TITLE
Fixed security issue and fixed overwriting.

### PR DESCRIPTION
**Pull request by joveice**
This should work.

I have tested it and it worked fine for me.
So now you will only change the values that you choose to change, and if the value does not exist it will skip it, so if you would like it to create it you will need to add that.
Do note that on L56 you no longer need the 'APP_LOG_LEVEL' in the .env file as it's changed out with LOG_CHANNEL and all the config is in a config file.
To support that you will need to change the form and the $data part.

### CODE REVIEW

**Comment by RachidLaasri** [comment]
Hello,

Thanks for you contribution.

I believe this can be achieved simply by adding

`Artisan::call('key:generate'); `

Right after this like:

`file_put_contents($this->envPath, $envFileData);`

What do you think?

**Comment by joveice** [comment]
I did try, but it asked for second parameter and I where unsuccessful to find what it was, especially since it doesn't make sense in my head to have two parameters on the key:generate command.

**Comment by RachidLaasri** [comment]
We already regenerating a new key on the final step.

https://github.com/RachidLaasri/LaravelInstaller/blob/master/src/Helpers/FinalInstallManager.php#L20

**Comment by joveice** [comment]
For those who care, this was fixed in #179 So it was indeed static as I thought. But that is no longer a concern.

**Pull request closed without merging**
